### ISSUE TITLE
Unpacked Dump link broken

### ISSUE THREAD

**Issue by athendrix** [pokiuwu/AuthHook-v176-StringPool#1]
Your unpacked dump link is broken.
It might also be helpful for future visitors to add how to make an unpacked dump on their own if it's not too crazy.

**Comment by pokiuwu** [comment]
too lazy to write a guide on how to unpack, as for the unpacked dump i dont have it anymore so

**Comment by athendrix** [comment]
Ok. Well for anyone finding this in the future, Magicmida seems to unpack v176 pretty well.
You need the full MapleStory v176 install for it to work though, and you have to run it as admin.
